name: Update Lockfiles Post-Dependabot
on: pull_request

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot-lockfile-update:
    runs-on: ubuntu-latest
    # if: github.actor == 'JordonPhillips' && contains(github.event.pull_request.title, 'python group')

    steps:
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Setup Python - 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Initialize Pants
        uses: pantsbuild/actions/init-pants@main
        with:
          # v0 makes it easy to bust the cache if needed
          # just increase the integer to start with a fresh cache
          gha-cache-key: v0
          named-caches-hash: ${{ hashFiles('python-default.lock') }}
          pants-ci-config: pants.ci.toml

      - name: Update Lockfiles
        run: make update-lockfiles

      - name: Commit and Push Changes
        if: test -n "$(git status --porcelain)"
        run: |
          git config user.name 'smithy-automation'
          git config user.email 'github-smithy-automation@amazon.com'
          git commit -m "Update lockfiles"
          git push

